/* Declarations for the embedded data files generated by 'dicer'.
 * I mean, dicer generates those files. These declarations are homemade.
 */
 
#ifndef DATA_H
#define DATA_H

// Decalsheet, unlike most resources, decodes into a live model rather than serial data.
// It's irrelevant to us, but Egg enforces a 256-decal limit per image. We'll exploit that and make every decalsheet a fixed length.
struct decal { int id,x,y,w,h; };
extern const struct decal decalsheet_sprites[256];
extern const struct decal decalsheet_font[256];

// Length always 256. Contains physics values indexed by map tile value. 0=vacant, 1=solid, 2=oneway
extern const unsigned char tilesheet_terrain[];
extern const int tilesheet_terrain_length;

// Map cells and annotations.
extern const int map_w;
extern const int map_h;
extern const unsigned char map[]; // map_w*map_h
extern const struct map_poi {
  int x,y;
  int cmd;
  int argv[4];
} map_poiv[];
extern const int map_poic;

// Verbatim data files. PNG or mp3 or whatever, for shovelling into Raylib's decoders.
extern const unsigned char image_sky[];
extern const int           image_sky_length;
extern const unsigned char image_terrain[];
extern const int           image_terrain_length;
extern const unsigned char image_sprites[];
extern const int           image_sprites_length;
extern const unsigned char image_logo[];
extern const int           image_logo_length;
extern const unsigned char image_font[]; // 16x6 glyphs of 8x12 each, first glyph is U+20
extern const int           image_font_length;

// Background images:
extern const unsigned char image_orbis_fixe[]; // Me first, motionless
extern const int           image_orbis_fixe_length;
extern const unsigned char image_clouds1[]; // Slowest
extern const int           image_clouds1_length;
extern const unsigned char image_clouds2[]; // Mediumest
extern const int           image_clouds2_length;
extern const unsigned char image_clouds3[]; // Fastest
extern const int           image_clouds3_length;
extern const unsigned char image_bgover[]; // Me last, motionless
extern const int           image_bgover_length;

// error image to make visually debugging textures easier
extern const unsigned char image_error[];
extern const int           image_error_length;

extern const unsigned char sound_blip[];
extern const int           sound_blip_length;
extern const unsigned char sound_boop[];
extern const int           sound_boop_length;
extern const unsigned char sound_arp[];
extern const int           sound_arp_length;
extern const unsigned char sound_fanfare[];
extern const int           sound_fanfare_length;

extern const unsigned char song_menu[];
extern const int           song_menu_length;
extern const unsigned char song_game[];
extern const int           song_game_length;
extern const unsigned char song_ending[];
extern const int           song_ending_length;

// Symbols for map_poiv.
#define CMD_SPRITE 1

// CMD_SPRITE, argv[0]=type
#define SPRITE_HERO 1
#define SPRITE_GHOST 2
#define SPRITE_PRINCESS 3
#define SPRITE_PUMPKIN 4
#define SPRITE_ROBOT 5
#define SPRITE_CLOWN 6

#endif
