/* Declarations for the embedded data files generated by 'dicer'.
 * I mean, dicer generates those files. These declarations are homemade.
 */
 
#ifndef DATA_H
#define DATA_H

// Decalsheet, unlike most resources, decodes into a live model rather than serial data.
// It's irrelevant to us, but Egg enforces a 256-decal limit per image. We'll exploit that and make every decalsheet a fixed length.
struct decal { int id,x,y,w,h; };
extern const struct decal decalsheet_sprites[256];

// Length always 256. Contains physics values indexed by map tile value. 0=vacant, 1=solid, 2=oneway
extern const unsigned char tilesheet_terrain[];
extern const int tilesheet_terrain_length;

// Map cells data. Length is always w*h ie 2400.
// TODO We'll find a neater way to capture the dimensions, and also extra attached data like spawn points.
#define map_w 80
#define map_h 40
extern const unsigned char map[];
extern const int map_length;

// Verbatim data tiles. PNG or mp3 or whatever, for shovelling into Raylib's decoders.
extern const unsigned char image_sky[];
extern const int           image_sky_length;
extern const unsigned char image_terrain[];
extern const int           image_terrain_length;
extern const unsigned char image_sprites[];
extern const int           image_sprites_length;

#endif
